data_paths:
  kiva_data: "data/kiva_loans.xlsx"
  world_bank_data: "data/world_bank_data.xlsx"
  processed_data: "data/processed/combined_data.csv"

model_params:
  logistic_regression:
    C: 1.0
    max_iter: 1000

output_paths:
  plots: "output/plots/"
  model: "model/logistic_model.pkl"
  predictions: "output/predictions.csv"
